# Generated by Django 4.2 on 2023-04-28 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInformation",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Students.student",
                    ),
                ),
                ("division", models.CharField(default=None, max_length=2)),
                ("phone", models.CharField(default=None, max_length=12)),
                ("email", models.EmailField(default=None, max_length=254, unique=True)),
                ("dob", models.DateTimeField(default=None)),
                ("bloodGroup", models.CharField(default=None, max_length=3)),
                ("permanentAddress", models.TextField(default=None)),
                ("localAddress", models.TextField(default=None)),
                ("fatherName", models.CharField(default=None, max_length=100)),
                ("foccupation", models.CharField(default=None, max_length=100)),
                ("fphone", models.CharField(default=None, max_length=12)),
                ("femail", models.EmailField(default=None, max_length=254)),
                ("motherName", models.CharField(default=None, max_length=100)),
                ("moccupation", models.CharField(default=None, max_length=100)),
                ("mphone", models.CharField(default=None, max_length=12)),
                ("memail", models.EmailField(default=None, max_length=254)),
                ("tenPercent", models.FloatField(default=None)),
                ("twelvePercent", models.FloatField(default=None)),
                ("feS1", models.FloatField(default=None)),
                ("feS2", models.FloatField(default=None)),
                ("seS1", models.FloatField(default=None)),
                ("seS2", models.FloatField(default=None)),
                ("teS1", models.FloatField(default=None)),
                ("teS2", models.FloatField(default=None)),
                ("beS1", models.FloatField(default=None)),
                ("beS2", models.FloatField(default=None)),
                ("achievements", models.TextField(default=None)),
                ("extraCurricular", models.TextField(default=None)),
            ],
        ),
    ]
